name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Submodule update
      run: git submodule init && git submodule update

    - name: Set Node.js 18.x
      uses: actions/setup-node@master
      with:
        node-version: 18.x

    - name: apt update
      run: sudo apt-get update

    - name: install libvirt
      run: sudo apt-get install -y libvirt-dev

    - name: npm install
      run: npm install

    - name: npm lint/bindings
      run: npm run lint/bindings
      continue-on-error: true

    - name: lint/examples
      run: npm run lint/examples

    - name: test
      run: npm run test
